### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by deratokati88** [deratokati88/protospace-32475#1]
gitのurl
https://github.com/deratokati88/protospace-32475
herokuのurl
https://protospace-32475.herokuapp.com/

**Comment by snkw-works** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ユーザーの詳細ページでは、登録したユーザーの名前が表示されるよう修正しましょう**
現状、以下の画像の赤で示した部分に「登録したユーザー名」が表示されない状態です。
<img width="1440" alt="スクリーンショット_2020-12-04_15_52_44" src="https://user-images.githubusercontent.com/54050089/101132124-c628b080-3649-11eb-9815-18bd65ffcfc1.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
